github: [metadata]
encoding: UTF-8

title: facedbook's blog
email: guweiyi_cn@hotmail.com
description: "Every failure is leading towards success."
url: "http://facedbook.github.io"
logo: /assets/img/logo.png

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

future: true
jailed: false

theme: jekyll-theme-minimal
gfm_quirks: paragraph_end

plugins: [jekyll-paginate]
paginate: 11
